version: '3'
services:
  web:
    build: .
    links:
      - redis
    ports:
      - "5000:5000"
      - "8000:8000"
    volumes:
      - ./src:/src
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"